version: 2.1

orbs:
  windows: circleci/windows@2.4.0

jobs:
  build-linux:
    docker:
      - image: plotly/plotly.net:ci
      
    steps:
      - checkout
      - run: "dotnet tool restore"
      - run: "dotnet paket restore"
      - run: "dotnet fake build -t BuildOnly"
      - run: "dotnet test"

  build-windows:
    executor: win/default
    steps:
      - checkout
      - run: dotnet tool restore
      - run: dotnet paket restore
      - run: dotnet fake build -t BuildOnly
      - run: dotnet test

workflows:
  version: 2
  Plotly.NET-build-test:
    jobs:
    - build-linux
    - build-windows