version: 2.1

jobs:
  build-linux:
    docker:
      - image: plotly/plotly.net:ci
      
    steps:
      - checkout
      - run: "dotnet tool restore"
      - run: "dotnet paket restore"
      - run: "dotnet fake build -t BuildOnly"
      - run: "dotnet test"

workflows:
  version: 2
  workflow:
    jobs:
    - build-linux