version: 2.1

jobs:
  build-linux:
    docker:
      - image: https://hub.docker.com/r/plotly/plotly.net
      
    steps:
      - checkout
      - run: "dotnet tool restore"
      - run: "dotnet paket restore"
      - run: "dotnet fake build -t BuildOnly"

workflows:
  version: 2
  workflow:
    jobs:
    - build-linux